### ISSUE TITLE
Implement a members-only ERC20 token

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/tinlake-erc20#2]
## Summary
This spec describes how we need to modify our standard DROP & TIN ERC20 contract to support the necessary functionality needed to comply with the securities restrictions most of our users use.

There are three key features:
* The token must have an `members` list, this is a list of addresses that are allowed to receive transfers. This can be changed/ammended by an authorized entity.
* The token must only allow transfers to and from members in the list. 
* Other contracts must be able to check if an address is in the members list. This is necessary to allow MakerDAO to limit its keeper auctions to the list of members or the Tinlake contracts to limit redemptions.
* A membership must have an expiration date. From a legal perspective a common validity of KYC checks is one year.
* An admin should be able to expire a membership but there must be a minimum delay (so that anyone being removed from the set has a chance to get rid of their tokens before).

## Members List
The members list is a simple contract that exposes a list of `members` that are allowed to receive tokens.

We should add a list of administrators to the token that can modify the member lists but not add or remove administrators.

```javascript=
contract MemberList {
    // use wards and ds-note
    constant uint48 minimumDelay = 60*60*24*7; // 7 day delay  
    mapping (address => uint48) members public;
    
    function updateMember(address usr, uint48 validUntil) public auth note {
        require(add(now, minimumDelay) < validUntil);
        members[usr] = validUntil;
    }

    function member(address usr) public {
        require(members[usr] >= now);
    }
}

contract MemberListLike {
    function members(address) public returns (uint48);
}
```

## Members-Only ERC20 
We should modify the `transfer`, `transferFrom`, `mint` function to verify that the `to` address is a valid member.

```
contract MembersOnlyERC20 {
    MemberListLike public memberlist;
    modifier checkMember(address user) { memberlist.member(usr); _; }

    function transferFrom(address from, address to, uint wad) checkMember(to) {
        //...
    }
}
```

**Comment by philipstanislaus** [comment]
LGTM, maybe we can call `time` => `lifetime` or `validUntil` and `minimumDelay` => `minLifetimeFromNow` or `minValidFromNow`?

**Comment by lucasvo** [comment]
I changed it to `validUntil` but the other variable shouldn't be renamed IMO.

**Comment by philipstanislaus** [comment]
Okay, no strong feelings :)
